### ISSUE TITLE
[Docs] 文档中：点击前往更深入的了解fields 链接跳转 404

### ISSUE THREAD

**Issue by ly525** [vipshop/ams#103]
[资源页面](https://vipshop.github.io/ams/api/resource.html)中的 【更深入的了解fields】链接： https://vipshop.github.io/ams/api/field.html 访问 404，
正确的是这个吗：https://vipshop.github.io/ams/field/

![image](https://user-images.githubusercontent.com/12668546/71821795-009e6c00-30ce-11ea-87f4-54286a328cfe.png)

**Comment by w3cmark** [comment]
已修复
