### ISSUE TITLE
[文档疑惑] 用于block级别作用域的fields，重置resource中的默认配置，貌似并未覆盖

### ISSUE THREAD

**Issue by ly525** [vipshop/ams#109]
复现 Demo：http://jsrun.pro/wKfKp/edit   ，    参见js 代码部分的第 71行

发现 blocks 的fields 字段并没有覆盖 resources 中的 fields 字段，和文档描述不太一致
[文档提及：用于block级别作用域的fields，重置resource中的默认配置](https://vipshop.github.io/ams/block/api.html#fields)

有点困惑，还请指点 😄

**Comment by w3cmark** [comment]
是可以覆盖的，你是不是看出block了？demo是有两个block：

![image](https://user-images.githubusercontent.com/7434649/72594153-bde85980-3941-11ea-974e-55235a010761.png)

**Comment by ly525** [comment]
@w3cmark 最新的，我把formEdit 这个block 移除了，感觉应该不是 block 看错了

![image](https://user-images.githubusercontent.com/12668546/72595890-cd69a180-3945-11ea-93db-5148b1cc2f9b.png)

**Comment by w3cmark** [comment]
@ly525 
block里定义的fields只会同名覆盖resource里的字段。如果要达到你隐藏 testRate 的目的，需要这样配置：
```js
 listBlock: {
    type: 'list',
    // 指定block使用的资源为上面声明的res
    resource: 'res',
    events: {
        init: '@list'
    },
    fields: {
        // 这里只会覆盖resource已经定义的同名field
        id: {
            type: 'text',
            label: '文本'
        },
        testRate: false // 直接设置为false
    }
}
```
