### ISSUE TITLE
[Bug Report] @ams-team/block-nav-user 404 not found

### ISSUE THREAD

**Issue by ly525** [vipshop/ams#112]
## 场景
通过 ams create demo 然后安装依赖的时候，提示这个包不存在

我在npm 上面搜索也没有这个包 @ams-team/block-nav-user

## 截图
![image](https://user-images.githubusercontent.com/12668546/75622004-88888a00-5bd6-11ea-962e-8f4a914260e1.png)

![image](https://user-images.githubusercontent.com/12668546/75622005-8b837a80-5bd6-11ea-8b0d-d4576a2f2b02.png)

## 解决方案
ams-cli 可能要更新下，用 ams create 的项目的 package.json 的依赖里面仍然有这个依赖

![image](https://user-images.githubusercontent.com/12668546/75622016-ae159380-5bd6-11ea-89c4-a8923ac22502.png)

**Comment by w3cmark** [comment]
@ams-team/cli@0.8.3亿修复
