### ISSUE TITLE
[求教] 列表区块的增删改查场景中，某个字段 编辑Dialog 和 显示在 Table 中，是否可以采用不同 type？

### ISSUE THREAD

**Issue by ly525** [vipshop/ams#113]
请教一个文档上没有提及的问题 😂（也许是有，我没有看到 😂）
一个比较常见的场景：
![image](https://user-images.githubusercontent.com/12668546/75756804-37aa9a00-5d6c-11ea-8f4e-ca1d331a0e46.png)

![image](https://user-images.githubusercontent.com/12668546/75756907-60329400-5d6c-11ea-9cd4-f8c328f8db3f.png)

有个表格，想对其进行增删改查

里面有个字段：是否经营中（status），在表格中显示：经营中、已停业

在编辑该项目的时候（operation-> editItem），调用了ams自带的 editItemDialog（通过如下方式调用）

```js
actions: {
    addItem: function({ item }) {
      this.callAction('addItemDialog')
    },
}
```

其中状态的 field 定义在 resource 中，如下

```js
fields: {
    'status': {
      'label': 'status',
      'type': 'text',
      htmlView(fieldValue, field, h) {
        const statusMap = {
          1: '营业中',
          2: '已停业'
        }
        return h('span', statusMap[fieldValue])
      }
    }
  },
```

想问下，在编辑的Dialog的 Form 中想实现 status 显示的是一个 select，而非是一个 input 该如何做呢？因为调用了 addItemDialog，重写 addItemDialog 的 fields 感觉可以实现，想问，有没有更直接的方式呢？（感觉ams暴露了更简单的 addItemDialog 应该有更直接的方式）

**Comment by w3cmark** [comment]
为啥需要这么麻烦？
正确的姿势：
status这个字段，在table中应该也设置为select类型，
```js
fields: {
    'status': {
      'label': 'status',
      'type': 'select',
      props: {
        options: {
          1: '营业中',
          2: '已停业'
        }
      }
    }
  }
```
这样配置后，在table中拿到的是“1”时就会显示成对应的文案“营业中”
拿到“2”，显示成对应的文案已停业”

**Comment by w3cmark** [comment]
> 这个我回去尝试一下，因为这样配置我认为会将表格的字段显示为 select 类型,而非一个文本类型。这个我尝试一下 谢谢

表格默认是view状态，它下面默认的field也都会展示为view状态的
