### ISSUE TITLE
[Bug Report] form label width not work?

### ISSUE THREAD

**Issue by ly525** [vipshop/ams#116]
提了个 issue，求大大解答 [Concerned] 

主要是想改下 Dialog 中 Form 的label-width
Form 文档：https://vipshop.github.io/ams/block/form.html

![image](https://user-images.githubusercontent.com/12668546/75962131-26919280-5efe-11ea-8855-0b6cc28f6a9f.png)

 form的 props: {'label-width': '400px'} 无法生效？

https://codepen.io/ly525/pen/XWbegLg?editors=1010

JS 部分搜索关键字 400

**Comment by w3cmark** [comment]
我看你上面的demo是生效的：
![image](https://user-images.githubusercontent.com/7434649/76160031-6efcba80-6161-11ea-96a7-863f7be2fd32.png)

**Comment by ly525** [comment]
不好意思 想今天早晨关闭的😄 应该是我调用的 dialog不对
