### ISSUE TITLE
如何在数据请求时，监听其失败返回，并做其他操作？

### ISSUE THREAD

**Issue by Pingze-github** [vipshop/ams#150]
比如希望数据接口返回403状态码，或code=指定值时，能够捕捉到状态，以进行跳转。（我这里要做登录跳转）
目前观察到：
+ 返回403状态码。无提示，不显示数据。
+ code=非0指定值。有tip提示，不显示数据。
没有找到办法捕获到这个状态并做跳转

**Comment by anymouschina** [comment]
本身有方法哇；
`
// 全局请求结果拦截器
                            if (ams.configs.resource.responseInterceptor) {
                                response = ams.configs.resource.responseInterceptor(
                                    response,
                                    options
                                );
                            }
`
使用方法就是初始化时,ams.config({
        resource:{
              responseInterceptor:fn
         }
})

**Comment by Pingze-github** [comment]
> 本身有方法哇；
> `// 全局请求结果拦截器 if (ams.configs.resource.responseInterceptor) { response = ams.configs.resource.responseInterceptor( response, options ); }`
> 使用方法就是初始化时,ams.config({
> resource:{
> responseInterceptor:fn
> }
> })

3Q~ 一开始没找到这个文档
