### ISSUE TITLE
移动端适配不好

### ISSUE THREAD

**Issue by Jetereting** [vipshop/ams#19]

**Comment by w3cmark** [comment]
移动端的后台需求场景比较少，我们一直想做移动端方面的东西，但是内部没啥需求场景，请问您可以详细描述一下您的移动需求场景么？

**Comment by Jetereting** [comment]
使用场景：比如交通工具上的时候用电脑会不方便，这时候会用手机操作后台管理系统

![image](https://user-images.githubusercontent.com/11585188/69927736-1e3b4d00-14f4-11ea-8e84-4bf37ecf45cd.png)

比如：如果判断为移动端，左边的导航就可以直接没有啦

**Comment by nuan1989** [comment]
看来不适合我.
