### ISSUE TITLE
👏👏👏欢迎加入 AMS 支持交流群

### ISSUE THREAD

**Issue by w3cmark** [vipshop/ams#7]
请扫二维码加入群：
![image](https://user-images.githubusercontent.com/7434649/63748192-7a7e4780-c8db-11e9-87a2-4b9e761c9e04.png)

如果上面二维码失效，请搜索添加群主 **viptech128**（备注 `AMS`），群主会拉你进群！

![image](https://user-images.githubusercontent.com/7434649/63748021-165b8380-c8db-11e9-9dc0-6dc4c7157f32.png)

**Comment by ly525** [comment]
@w3cmark Hi，非常赞的项目，已经申请加群了，貌似两天了没有回复哦。麻烦看下呢

**Comment by SHERlocked93** [comment]
这是 QQ 的二维码还是微信的啊～
