### ISSUE TITLE
文本的各种提示配置

### ISSUE THREAD

**Issue by EdwardQ** [vipshop/ams#94]

**Comment by wuzebin** [comment]
- input框中placehold的提示

- info的提示，加在label处的左边

- desc的提示，加在input框下边

```js
{
  type: 'text',
  label: 'text',
  props: {
    info: '加在label处的左边',
    desc: '加在input框下边',
    placeholder: 'placehold的提示'
  }
}
```

- 文本类型（type：text）还可以在[展示状态下后面追加提示icon](https://codepen.io/w3cmark/pen/yLLyKmW)
