### ISSUE TITLE
想请教下如何修改(适配)接口规范

### ISSUE THREAD

**Issue by ly525** [vipshop/ams#97]
首先非常感谢唯品会开源如此优秀的项目，感谢各位作者的辛苦付出，我正在把它接入到实际的项目中，遇到了一些和接口适配相关的疑惑，还想请教下：

AMS 的接口[规范](https://vipshop.github.io/ams/api/api.html#%E9%80%9A%E7%94%A8%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84) 是这样的：

```js
{
    "code": 0, 
    "data": {
        ...
    },
    "msg": "success"
}
```

而我们已经上线了的项目接口是这样的:
`code`(AMS) -> `status`(我们的项目约定)

```js
{
    "status": 0, 
    "data": {
        ...
    },
    "msg": "success"
}
```

示意图：
---
![image](https://user-images.githubusercontent.com/12668546/71654443-cf8c0780-2d6c-11ea-8e28-c8cb4391a411.png)
---

想请教下，该如何修改，才能适配我们现在已有的项目接口呢？非常感谢

**Comment by w3cmark** [comment]
方法一：通过配置全局请求结果拦截器
```js
ams.config({
    resource: {
        /**
         * 全局请求结果拦截器，只能有一个，新配置的会覆盖旧的，返回空会中断后续处理，不处理的场景返回res
         */
        responseInterceptor(res) {
            return {
               ...res,
                code: res.status
            };
        }
    }
})
```

具体文档：https://vipshop.github.io/ams/api/ams-config.html

**Comment by EdwardQ** [comment]
可以通过全局的拦截器去修改respose
```js
// 全局配置拦截器，登录需要判断
ams.config({
    resource: {
        responseInterceptor(res) {
            // console.log('responseInterceptor', res)
            // 响应的拦截，添加code响应字段
            res.data.code = res.data.status
            return res
        },
        requestInterceptor(options) {
            // console.log('requestInterceptor', options)
            // 请求的拦截，添加请求头，未登录返回数据
            options.headers = {
                ...options.headers,
                'X-Requested-With': 'XMLHttpRequest' // 表明是AJax异步，后端用来返回未登录数据
            }
            options.params = {
                ...options.params
                // 'ticket': ams.utils.getQueryString('ticket')
            }
            return options
        }
    }
})
```

**Comment by ly525** [comment]
@w3cmark @EdwardQ 

收到，不好意思，刚才在读文档，看到了有全局配置的地方。正在尝试，非常感谢

另外再想补充问一下，通过 ams.config 来配置类似 axios 的拦截器，是否会对原有项目中的 axios 有影响？（这个我等下去做一下尝试 😂）

**Comment by w3cmark** [comment]
> @w3cmark @EdwardQ
> 
> 收到，不好意思，刚才在读文档，看到了有全局配置的地方。正在尝试，非常感谢
> 
> 另外再想补充问一下，通过 ams.config 来配置类似 axios 的拦截器，是否会对原有项目中的 axios 有影响？（这个我等下去做一下尝试 😂）

不会的，ams内部没有使用axios。

**Comment by ly525** [comment]
@w3cmark 收到

@w3cmark @EdwardQ 非常感谢两位的解答，我去尝试下。如果没有问题，我等下会关闭 issue，再次感谢
