### ISSUE TITLE
文档增强：建议在文档导航部分增加 GitHub 链接

### ISSUE THREAD

**Issue by ly525** [vipshop/ams#98]
小建议：
1. 建议[文档](https://vipshop.github.io/ams/)在如下位置增加 GitHub 链接，虽然首页有了，但是在读里面具体文档的时候，想跳转到 repo，会有些麻烦，建议加一下。

![image](https://user-images.githubusercontent.com/12668546/71655205-cbfa7f80-2d70-11ea-821d-86b8ec52bd87.png)

2. 在 [Demo](https://vipshop.github.io/ams/example) 的导航位置也添加 GitHub 链接。原因：看到了Demo 效果，想看下代码是如何实现的，但需要重新找下 ams 的repo，感觉添加下 repo 的链接，直接点过去会更方便

**Comment by w3cmark** [comment]
好的

**Comment by w3cmark** [comment]
> 小建议：
> 
> 1. 建议[文档](https://vipshop.github.io/ams/)在如下位置增加 GitHub 链接，虽然首页有了，但是在读里面具体文档的时候，想跳转到 repo，会有些麻烦，建议加一下。
> 
> ![image](https://user-images.githubusercontent.com/12668546/71655205-cbfa7f80-2d70-11ea-821d-86b8ec52bd87.png)
> 
> 1. 在 [Demo](https://vipshop.github.io/ams/example) 的导航位置也添加 GitHub 链接。原因：看到了Demo 效果，想看下代码是如何实现的，但需要重新找下 ams 的repo，感觉添加下 repo 的链接，直接点过去会更方便

好的～

**Comment by w3cmark** [comment]
已添加
