### ISSUE TITLE
example 文档疑惑？

### ISSUE THREAD

**Issue by ly525** [vipshop/ams#99]
请教下，这段话没太看懂？
![image](https://user-images.githubusercontent.com/12668546/71656287-c3587800-2d75-11ea-9fb7-0561d09473f5.png)

**Comment by w3cmark** [comment]
example目录介绍：
```sh
- example
-- dev      // packages组件本地开发调试服务，在ams根目录执行 npm run dev 命令跑的就是这里的文件
-- mobile // 移动端示例
-- router  // PC端示例
```

> 请教下，这段话没太看懂？
> ![image](https://user-images.githubusercontent.com/12668546/71656287-c3587800-2d75-11ea-9fb7-0561d09473f5.png)

这里文档描述有点歧义。
example目录介绍：
```sh
- example
-- dev      // packages组件本地开发调试服务，在ams根目录执行 npm run dev 命令跑的就是这里的文件
-- mobile // 移动端示例
-- router  // PC端示例
```

**Comment by ly525** [comment]
@w3cmark 好的，感谢解答，可以更新下文档😄
